### ISSUE TITLE
Order: strange behavior

### ISSUE THREAD

**Issue by kaelig** [Shopify/web-foundation#94]
I found a weird linting behavior with stylelint-config-shopify (seen in polaris-styleguide):

```scss
// No errors (ideally, should throw an error because letter-spacing should be last)
.foo {
  letter-spacing: 0.1rem;
  position: absolute;
  display: block;
}

// Throws an error
// [stylelint] Expected "position" to come before "display" (order/properties-order) [order/properties-order]
.foo {
  letter-spacing: 0.1rem;
  display: block;
  position: absolute;
}

// And auto-fixes to this (as expected):
.foo {
  position: absolute;
  display: block;
  letter-spacing: 0.1rem;
}
``` 

It must come from a config issue in https://github.com/Shopify/stylelint-config-shopify/blob/master/rules/order.js, but I’m not sure how to fix it.
